name: The Nears
favicon: null
layout_spectrum: 0.86078
typography_spectrum: 0.52454
title: 'We are...the Nears!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0086ff'
    - '#ff6a63'
    - '#0d0b16'
    - '#ffdd88'
    - '#6c42b8'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
