name: The Nears
favicon: null
layout_spectrum: 0.3304778756573796
typography_spectrum: 0.8970804254058748
title: 'We are...the Nears!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff5f2b'
    - '#3f285e'
    - '#ffb823'
    - '#e82128'
    - '#19908a'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
